# Generated by Django 4.2 on 2023-04-04 17:04

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('pd_id', models.CharField(max_length=50)),
                ('batch_id', models.CharField(max_length=50)),
                ('timestamp', models.CharField(max_length=50)),
                ('product_details', models.CharField(max_length=50)),
                ('hash_code', models.CharField(max_length=50)),
                ('owned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BlockChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash1', models.CharField(max_length=50)),
                ('hash2', models.CharField(max_length=50)),
                ('hash3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('mobile', models.CharField(max_length=15)),
                ('num_owned', models.IntegerField(default=0)),
                ('products', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
    ]
