# Generated by Django 4.2 on 2023-04-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_blockchain_hash1_alter_blockchain_hash2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='hash_code',
            field=models.CharField(max_length=1000),
        ),
    ]
