# Generated by Django 4.2 on 2023-04-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_blockchain_hash1_alter_blockchain_hash2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='batch_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='block',
            name='pd_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='block',
            name='product_details',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='block',
            name='timestamp',
            field=models.CharField(max_length=100),
        ),
    ]
