# Generated by Django 4.2 on 2023-04-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_block_batch_id_alter_block_pd_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='hash_code',
            field=models.CharField(max_length=500),
        ),
    ]
