# Generated by Django 4.2 on 2023-04-05 17:51

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_alter_block_hash_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='block',
            name='owned',
        ),
        migrations.AddField(
            model_name='block',
            name='owner',
            field=models.CharField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='block',
            name='product_details',
            field=django.contrib.postgres.fields.hstore.HStoreField(),
        ),
    ]
