# Generated by Django 4.2 on 2023-04-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='hash_code',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
