# Generated by Django 4.2 on 2023-04-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_alter_block_hash_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('loc', models.CharField(max_length=32)),
                ('report', models.CharField(max_length=500)),
            ],
        ),
    ]
