# Generated by Django 4.2 on 2023-04-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_alter_block_batch_id_alter_block_pd_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='batch_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='block',
            name='hash_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='pd_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='block',
            name='timestamp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='hash1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='hash2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='hash3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reports',
            name='loc',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='reports',
            name='username',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
