# Generated by Django 4.2 on 2023-04-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_alter_block_batch_id_alter_block_hash_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockChain',
        ),
    ]
