# Generated by Django 4.2 on 2023-04-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='hash_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
