# Generated by Django 4.2 on 2023-04-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_alter_block_hash_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='timestamp',
            field=models.CharField(max_length=30),
        ),
    ]
