# Generated by Django 4.2 on 2023-04-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_alter_block_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='timestamp',
            field=models.CharField(default='00-00-0000 00:00:0000', max_length=50),
            preserve_default=False,
        ),
    ]
